version: "3.8"

services:
  backend:
    build:
      context: ./app-itself
    ports:
      - "5000:5000"
    volumes:
      - ./app-itself:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: npm run dev
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=maslo
      - MYSQL_DATABASE=quizdb
    ports:
      - "3280:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

    


  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db


volumes:
  mysql_data:
  mongo_data: